---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
APPLY_FIXES: none
DISABLE_LINTERS:
  - SPELL_CSPELL
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
