#!/bin/sh
ADDONNAME=homebridge
PREFIX=/usr/local
ADDON_DIR=${PREFIX}/addons/${ADDONNAME}
ADDONWWW_DIR=${PREFIX}/etc/config/addons/www/${ADDONNAME}
RCD_DIR=${PREFIX}/etc/config/rc.d
EXEC=${PREFIX}/bin/hb-service
EXECARGS="--user-storage-path $ADDON_DIR --allow-root run"
PIDFILE=/var/run/hb-service.pid

start() {
	logger -t homebridge -p user.info "start $ADDONNAME"
	# shellcheck disable=SC2086 # word split on spaces wanted for $EXECARGS
	start-stop-daemon --start --oknodo --make-pidfile --background --pidfile "$PIDFILE" --exec "$EXEC" -- $EXECARGS
}

stop() {
	start-stop-daemon --stop --oknodo --retry 5 --pidfile "$PIDFILE"
	logger -t homebridge -p user.info "stopped $ADDONNAME"
}

restart() {
	stop
	sleep 10
	start
}

info() {
	VER=$(cat ${ADDON_DIR}/VERSION)
	PORT=$(jq '.platforms[] | select(.platform="config").port' ${ADDON_DIR}/config.json)
	echo "Info: Homebridge running on your Homematic controller"
	echo "Name: hm-homebridge-addon"
	echo "Version: ${VER}"
	echo "Operations: restart uninstall"
	echo "Config-Url: /addons/${ADDONNAME}/index.html?p=${PORT}"
	echo "Update: /addons/${ADDONNAME}/update-check.cgi"
}

uninstall() {
	stop
	rm -rf ${ADDON_DIR}
	rm -rf ${ADDONWWW_DIR}
	rm -f ${RCD_DIR}/S98Homebridge
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart | reload)
	restart
	;;
info)
	info
	;;
uninstall)
	uninstall
	;;
*)
	echo "Usage: $0 {start|restart|stop|info}"
	exit 1
	;;
esac

exit $?
