#!/bin/sh

ADDONNAME=homebridge
PREFIX=/usr/local
ADDONCONFIG_DIR=${PREFIX}/etc/config/addons/${ADDONNAME}

mount | grep ${PREFIX}
if [ $? -eq 1 ]; then
	mount ${PREFIX}
fi

mkdir -p ${ADDONCONFIG_DIR}
chmod 755 ${ADDONCONFIG_DIR}
# redirect all output to log file
exec >${ADDONCONFIG_DIR}/${ADDONNAME}-install.log 2>&1

# copy content of package to config directory
cp -af homebridge ${ADDONCONFIG_DIR}/homebridge
chmod +x ${ADDONCONFIG_DIR}/homebridge
cp -af fake-sudo ${ADDONCONFIG_DIR}/fake-sudo
chmod +x ${ADDONCONFIG_DIR}/fake-sudo
cp -af index.html ${ADDONCONFIG_DIR}/index.html
cp -af update-check.cgi ${ADDONCONFIG_DIR}/update-check.cgi
chmod +x ${ADDONCONFIG_DIR}/update-check.cgi
cp -af VERSION ${ADDONCONFIG_DIR}/VERSION

# finish installation
cd /
${ADDONCONFIG_DIR}/homebridge install

# wait until Homebridge has started
sleep 5
sync

# check installation
${ADDONCONFIG_DIR}/homebridge info

# force restart after installation
exit 10
