---
# This is a linting workflow

name: Lint

# Controls when the workflow will run
on:  # yamllint disable-line rule:truthy
  # Triggers the workflow on push or pull request events but only for "main"
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains jobs related to linting
  markdown:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run mdl
        uses: bewuethr/mdl-action@v1

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0

  yaml:
    name: Yaml lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run yaml-lint
        uses: ibiqlik/action-yamllint@v3
