---
# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
name: MegaLinter

on:
  # Trigger mega-linter at every push. Action will also be visible from Pull Requests to master
  push: # Comment this line to trigger action only on pull-requests (not recommended if you don't pay for GH Actions)
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # If you use VALIDATE_ALL_CODEBASE = true, you can remove this line to improve performances

      # Find shell scripts with shebang for MegaLinter
      - name: Find shell scripts
        shell: bash
        env:
          SHEBANGREGEX: "^#! */[^ ]*/(env *)?[abk]*sh"
        run: |
          SCRIPT_FILES=""
          SEPARATOR="|"
          while IFS= read -r -d '' file; do
            head -n1 "$file" | grep -Eqs "$SHEBANGREGEX" || continue
            SCRIPT_FILES="$SCRIPT_FILES${SEPARATOR}($file)"
          done < <(find -- contents/* \
              -type f ! -name '*.*' \
              -print0)
          SCRIPT_FILES_REGEX="${SCRIPT_FILES:${#SEPARATOR}}" # remove leading separator
          {
            echo "BASH_EXEC_FILE_EXTENSIONS=['']"
            echo "BASH_EXEC_FILTER_REGEX_INCLUDE='$SCRIPT_FILES_REGEX'"
            echo "BASH_SHELLCHECK_FILE_EXTENSIONS=['']"
            echo "BASH_SHELLCHECK_FILTER_REGEX_INCLUDE='$SCRIPT_FILES_REGEX'"
          } >> "$GITHUB_ENV"

      # MegaLinter
      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter/flavors/documentation@v6
        env:
          # All available variables are described in documentation
          # https://megalinter.io/configuration/
          VALIDATE_ALL_CODEBASE: true # Set ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} to validate only diff with main branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ADD YOUR CUSTOM ENV VARIABLES HERE TO OVERRIDE VALUES OF .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
